Aura + CLI
NickvisionApps/Cavalier pull request #50
Opened 2023-07-25 21:44 UTC by fsobolev

Commits got messed on another branch so I created new one and copied everything in one commit.

There are still things to do, so it's a draft for now.

Notes:
* In `PreferenceDialog` the loading was changed: first all signals get connected, then all values get loaded and set. The same method is called when Cavalier receives command-line arguments, so the UI gets completely updated.
* CLI option that accept boolean value require explicit value, just `-f` will not work for example, needs `-f true`. It is possible to make "flags" using CommandLine, but they work as 2 state switches: true or false, with one of them being default. Here we actually need 3 states: do not change, change to true and change to false, that's why explicit value is required.
* I use separate `CmdOptions` instead of `Configuration` because: a) options should be nullable so I can check whether they were used in command or not; b) not all configuration values should be exposed as command; c) some options have different types/values (like roundness which is 0-100 int in command but 0.0-1.0 float in configuration).

Closes #44

2023-07-25 21:47 UTC, nlogozzo commented on NickvisionCavalier.GNOME/NickvisionCavalier.GNOME.csproj
> +    <PackageReference Include="Nickvision.Aura" Version="2023.7.0" />
nuget-sources needs update :)

2023-07-25 22:16 UTC, DaPigGuy commented on NickvisionCavalier.Shared/Models/CmdOptions.cs
> +    /// Roundness of items (0 - square, 1 - round)
```suggestion
    /// Roundness of items (0 - square, 100 - round)
```

Looks like this should be 100?

2023-07-25 22:16 UTC, DaPigGuy commented on NickvisionCavalier.Shared/Models/CmdOptions.cs
> +    [Option('d', "drawing-mode", Required = false, HelpText = "Drawing more, one of: wavebox, levelsbox, particlesbox, spinebox, barsbox")]
```suggestion
    [Option('d', "drawing-mode", Required = false, HelpText = "Drawing mode, one of: wavebox, levelsbox, particlesbox, spinebox, barsbox")]
```

2023-07-25 22:16 UTC, fsobolev commented on NickvisionCavalier.Shared/Models/CmdOptions.cs
> +    /// Roundness of items (0 - square, 1 - round)
right, here it's 100

2023-07-25 23:42 UTC, fsobolev commented
If the user starts the first instance of Cavalier with `--help` option or with any option that contains error, help will be printed to console and the app will not start. If the same is done while Cavalier is already running, this dialog will appear.

![image](https://github.com/NickvisionApps/Cavalier/assets/117388856/71f204f3-90fc-44b9-b61c-d9ce8835e74a)

2023-07-26 01:42 UTC, fsobolev commented
Rarely, but still sometimes CAVA wasn't stopping together with the app, latest commit will hopefully fix it. From the docs:

> The [Kill](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.kill?view=net-7.0) method executes asynchronously. After calling the Kill method, call the [WaitForExit](https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.waitforexit?view=net-7.0) method to wait for the process to exit

I'm going to update changelog and then the PR is ready for review. Depends on https://github.com/NickvisionApps/Aura/pull/4 but other than saving config everything works.

2023-07-26 15:55 UTC, nlogozzo requested changes

2023-07-26 15:55 UTC, nlogozzo commented on NickvisionCavalier.Shared/Controllers/MainWindowController.cs
> +    private readonly PreferencesViewController _preferencesViewController;
Turn this into a public get, init property.

```
public PreferencesViewController PreferencesViewController { get; init; }
```

Then you can also remove the `GetPreferencesViewController()` method.

2023-07-26 16:21 UTC, fsobolev commented
> The scroll window inside a MessageDialog looks weird IMO...could you make it like the style of the CorruptedFilesDialog/HistoryDialog?

![image](https://github.com/NickvisionApps/Cavalier/assets/117388856/8646dfbf-f41d-4066-8239-4bb6d27aa43b)

2023-07-26 16:36 UTC, nlogozzo commented
> > The scroll window inside a MessageDialog looks weird IMO...could you make it like the style of the CorruptedFilesDialog/HistoryDialog?
> 
> ![image](https://github.com/NickvisionApps/Cavalier/assets/117388856/8646dfbf-f41d-4066-8239-4bb6d27aa43b)
> 

Beautiful! Since there's no description however, maybe we don't need to have the scroll window with the `view` background...

2023-07-26 16:39 UTC, fsobolev commented
> Since there's no description however, maybe we don't need to have the scroll window with the view background...

But we still have heading and empty headerbar that don't scroll and should not. IMO this dialog template works good even without description.

2023-07-26 16:42 UTC, nlogozzo approved these changes

2023-07-26 16:42 UTC, merged